/*
 * NOTE: This file is autogenerated by cbindgen.
 *
 * Foxglove SDK
 * https://github.com/foxglove/foxglove-sdk
 */


#ifndef FOXGLOVE_H
#define FOXGLOVE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct foxglove_websocket_server foxglove_websocket_server;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create and start a server. The server must later be freed with `foxglove_server_free`.
 *
 * `port` may be 0, in which case an available port will be automatically selected.
 *
 * # Safety
 * `name` and `host` must be null-terminated strings with valid UTF8.
 */
struct foxglove_websocket_server *foxglove_server_start(const char *name,
                                                        const char *host,
                                                        uint16_t port);

/**
 * Get the port on which the server is listening.
 */
uint16_t foxglove_server_get_port(const struct foxglove_websocket_server *server);

/**
 * Free a server created via `foxglove_server_start`.
 *
 * If the server has not already been stopped, it will be stopped automatically.
 */
void foxglove_server_free(struct foxglove_websocket_server *server);

/**
 * Stop and shut down a server.
 */
void foxglove_server_stop(struct foxglove_websocket_server *server);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FOXGLOVE_H */
